spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  thymeleaf:
    cache: false
  profiles:
    active: local
   
#####################   
auth-server: http://localhost:18085
#####################
security:
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      scope: demoScope
#      user-authorization-uri: ${auth-server}/oauth/authorize
#      authorized-grant-types: authorization_code
#    authorization:
#      check-token-access: permitAll()
    resource:
      token-type:  bearer
      token-info-uri: ${auth-server}/oauth/check_token
      user-info-uri:  ${auth-server}/api/user
      id: authServerResource
###########################      
logging:
  level:
    org.springframework.security: DEBUG
###########################    
session:
  cookie:
    name: UISESSION
    
server:
  tomcat:
    accesslog: 
      enabled : true
    